language: cpp
compiler:
  - gcc-4.8
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libboost-dev
install:
  - if [ "$CXX" = "g++" ]; then
       export CXX="g++-4.8";
    fi
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - make
