sudo: required
dist: trusty
language: cpp
compiler:
  - gcc-4.9
  - clang-3.5
before_install:
  - sudo add-apt-repository ppa:afrank/boost -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.9 clang-3.5 libclang-3.5-dev libgcc-4.8-dev libstdc++-4.8-dev libboost1.57-all-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
script:
  - if [ "$CXX" = "g++" ]; then
       export CXX="g++-4.9";
    fi
  - if [ "$CXX" = "clang++" ]; then
       export CXX="clang++-3.5";
    fi
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - VERBOSE=1 make
