sudo: required
dist: trusty
language: cpp
compiler:
  - gcc-5
  - clang-3.6
before_install:
  - sudo add-apt-repository ppa:afrank/boost -y
  - sudo apt-get update -q
  - apt-cache search g++
  - apt-cache search clang
  - apt-cache search libstdc++
  - apt-cache search libboost
  - sudo apt-get install g++-5 clang-3.6 libstdc++-5 libboost1.57-all-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
script:
  - if [ "$CXX" = "g++" ]; then
       export CXX="g++-5";
    fi
  - if [ "$CXX" = "clang++" ]; then
       export CXX="clang++-3.6";
    fi
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - VERBOSE=1 make
