language: cpp
compiler:
  - gcc-4.9
  - clang
before_install:
  - sudo add-apt-repository ppa:afrank/boost -y
  - sudo apt-get update -q
  - sudo apt-get install libboost1.57-all libboost1.57-all-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
script:
  - if [ "$CXX" = "g++" ]; then
       export CXX="g++-4.9";
    fi
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - VERBOSE=1 make
