language: cpp
compiler:
  - gcc-5
  - clang
before_install:
  - sudo add-apt-repository ppa:afrank/boost -y
  - sudo apt-get update -q
  - sudo apt-get install libboost1.57-all libboost1.57-all-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - clang-3.6
    - libstdc++-5
script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - VERBOSE=1 make
