language: cpp
compiler:
  - gcc-5
  - clang
before_install:
  - sudo add-apt-repository ppa:apw/boost -y
  - sudo apt-get update -q
  - sudo apt-get install boost1.58
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
  - if [ "$CXX" = "g++" ]; then
       export CXX="g++-5";
    fi
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - VERBOSE=1 make
